name: Android each commit workflow

on:
  push:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint
        run: bash ./gradlew ktlintCheck

#     App module
      - name: Upload Android app module lint results
        uses: actions/upload-artifact@v4
        with:
          name: lintAppModule
          path: |
            androidApp/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.txt
            androidApp/build/reports/ktlint/ktlintTestSourceSetCheck/ktlintTestSourceSetCheck.txt

#     Shared module
      - name: Upload shared module lint results
        uses: actions/upload-artifact@v4
        with:
          name: lintSharedModule
          path: |
            shared/build/reports/ktlint/ktlintAndroidMainSourceSetCheck/ktlintAndroidMainSourceSetCheck.txt
            shared/build/reports/ktlint/ktlintAndroidUnitTestSourceSetCheck/ktlintAndroidUnitTestSourceSetCheck.txt
            shared/build/reports/ktlint/ktlintCommonMainSourceSetCheck/ktlintCommonMainSourceSetCheck.txt
            shared/build/reports/ktlint/ktlintCommonTestSourceSetCheck/ktlintCommonTestSourceSetCheck.txt
            shared/build/reports/ktlint/ktlintIosMainSourceSetCheck/ktlintIosMainSourceSetCheck.txt
            shared/build/reports/ktlint/ktlintIosTestSourceSetCheck/ktlintIosTestSourceSetCheck.txt
            shared/build/reports/ktlint/ktlintKotlinScriptCheck/ktlintKotlinScriptCheck.txt
