name: Android each commit workflow

on:
  push:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint
        run: bash ./gradlew ktlintCheck

#     App module
      - name: Upload source lint results
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: androidApp/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.txt
      - name: Upload test lint results
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: androidApp/build/reports/ktlint/ktlintTestSourceSetCheck/ktlintTestSourceSetCheck.txt